services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - MONGO_URI=mongodb://mongo:27017/project_mern 
    depends_on:
      - mongo
    networks:
      - mern_network

  mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017" 
    volumes:
      - mongo_data:/data/db
    networks:
      - mern_network
  
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=user
      - ME_CONFIG_BASICAUTH_PASSWORD=user
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongo
    networks:
      - mern_network

volumes:
  mongo_data:

networks:
  mern_network: